apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffe-shop
  labels:
    app: coffe-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffe-shop
  template:
    metadata:
      labels:
        app: coffe-shop
    spec:
      containers:
        - name: coffe-shop
          image: cristianorr25/coffe-shop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: coffe-shop-service
  name: coffe-shop-service
spec:
  ports:
    - name: "3000-3000"
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
  selector:
    app: coffe-shop
  sessionAffinity: None
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coffe-shop-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: k3s.cloufly.dev.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coffe-shop-service
                port:
                  number: 30000
