name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $(grep 'ansible_host=' ansible/inventory | awk -F'ansible_host=' '{print $2}' | awk '{print $1}') >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/setup-k3s.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/coffe-shop:latest .
          docker push ghcr.io/${{ github.repository }}/coffe-shop:latest

  kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          version: '1.25.0'  # Ajuste a versão conforme necessário

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/prometheus-configmap.yaml
          kubectl apply -f kubernetes/prometheus-deployment.yaml
          kubectl apply -f kubernetes/prometheus-service.yaml
          kubectl apply -f kubernetes/grafana-deployment.yaml
          kubectl apply -f kubernetes/grafana-service.yaml
          kubectl apply -f kubernetes/coffe-shop-deployment.yaml
          kubectl apply -f kubernetes/coffe-shop-service.yaml
          kubectl apply -f kubernetes/coffe-shop-ingress.yaml
