name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $(grep 'ansible_host=' ansible/inventory | awk -F'ansible_host=' '{print $2}' | awk '{print $1}') >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/setup-k3s.yml

  build-and-deploy:
          runs-on: ubuntu-latest
      
          steps:
            - name: Checkout code
              uses: actions/checkout@v3
      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
      
            - name: Build Docker image
              run: |
                docker buildx build --tag ghcr.io/${{ github.repository_owner }}/coffe-shop:latest ./app --push
      
            - name: Authenticate with GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
    
