name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  setup-k3s-with-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $(grep 'ansible_host=' ansible/inventory | awk -F'ansible_host=' '{print $2}' | awk '{print $1}') >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/setup-k3s.yml

  build-and-push-coffe-app:
    runs-on: ubuntu-latest
    needs: setup-k3s-with-ansible
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/coffe-shop:latest ./app

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/coffe-shop:latest        

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-coffe-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.30.4/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/coffe.yml
          kubectl apply -f kubernetes/grafana.yml
          kubectl apply -f kubernetes/prometheus.yml
