name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: "ghcr.io"
  CI_REGISTRY_IMAGE: "ghcr.io/cristianorodrigues25/k3s-deploy-github"  

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $(grep 'ansible_host=' ansible/inventory | awk -F'ansible_host=' '{print $2}' | awk '{print $1}') >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory ansible/setup-k3s.yml

  build-and-deploy:
          runs-on: ubuntu-latest
          permissions:
            contents: read
            packages: write
      
          steps:
            - name: Checkout code
              uses: actions/checkout@v3
      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin              
      
            - name: Build and push Docker image
              
              working-directory: ./app
              run: |
                DOCKER_BUILDKIT=1 docker build -t ghcr.io/${{ env.CI_REGISTRY_IMAGE }}/${{ github.ref }} .
                docker push ghcr.io/${{ env.CI_REGISTRY_IMAGE }}/${{ github.ref }}
          
    
